### ISSUE TITLE
CityDatabase v3.3.1 build 1: Failed to read texture file

### ISSUE THREAD

**Issue by naipin** [3dcitydb/importer-exporter-postgis#3]
Hi

Using KML/COLLADA/glTF Export,  I was able to export a single building with the texture and view with open3mod.

With Bounding Box export, i encountered many instances of 
[date/time] Failed to read texture file: _yyy where yyy was the name of the original file. 

The exported buildings are displayed in Cesium as vanilla white without textures.

Is it due to folder not created or permission issue?

Thank you.

**Comment by yaozhihang** [comment]
This error message shows that the texture files cannot be found and read from the database. Have you got any error messages while importing your CityGML file into the 3DCityDB database?

**Comment by naipin** [comment]
There are no error messages. 

I can see the textures in the collada file generated for a single building. 

When I used the Export function (the second tab), I can see the textures that are extracted in the folder.

Is there a tmp folder or similar that is required to hold the images that needs to be there? I am using Windows 10.

**Comment by yaozhihang** [comment]
Could you send me your CityGML datasets for tests? 
zhihang.yao@tum.de

**Comment by clausnagel** [comment]
no response so closing this issue
